const preloadedData = [
  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_e6f2680d029736fca03758483f43b336',
      label: 'Dinner Tonight: The Dagwood Sandwich Recipe',
      image: 'https://www.seriouseats.com/thmb/FlWeiby7mRlbzYO0GB-DMwI7KME=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2013__09__20110502-127355-dinner-tonight-dagwood-easy-packed-lunches-02-e71c6ddd41f648d0bfe882ba987632de.jpg',
      source: 'Serious Eats',
      url: 'http://www.seriouseats.com/recipes/2011/05/the-dagwood-sandwich-recipe.html',
      shareAs: 'http://www.edamam.com/recipe/dinner-tonight-the-dagwood-sandwich-recipe-e6f2680d029736fca03758483f43b336/sandwich',
      ingredientLines: [
        '3 slices rye sandwich bread',
        '2 tablespoons yellow mustard',
        '1 tablespoon mayonnaise',
        '4 slices deli ham',
        '2 slices American cheese',
        '2 leaves iceberg lettuce',
        '4 slices bologna',
        '4 slices salami',
        '6 dill pickle chips',
        '3 slices tomato',
        '4 slices turkey',
        '2 slices Swiss cheese',
        '2 pimiento stuffed green olives',
      ],
      calories: 1907.6873888868838,
    },
  }, {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_e371a068dfe3a72ce90b5d9295dee35f',
      label: 'Classic Club Sandwich Recipe',
      image: 'https://www.seriouseats.com/thmb/smaTiQJB4xWK8M9WlZICrOrqyIc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2012__10__20121105-127677-Club-Sandwich-PRIMARY-30eb87ffe7654d8dadc42ba8c0b0fd85.jpg',
      source: 'Serious Eats',
      url: 'http://www.seriouseats.com/recipes/2012/11/classic-club-sandwich-recipe.html',
      shareAs: 'http://www.edamam.com/recipe/classic-club-sandwich-recipe-e371a068dfe3a72ce90b5d9295dee35f/club+sandwich',
      yield: 8,
      ingredientLines: [
        '6 slices (about 1/2-inch thick) white Pullman loaf',
        '6 tablespoons mayonnaise',
        '1 tablespoon mustard (optional)',
        '4 large leaves greenleaf lettuce',
        '3 ounces thickly sliced deli turkey',
        '6 strips thick-cut bacon, cooked until crisp',
        '1 large beefsteak tomatoes (about 6 ounces), sliced',
        'Salt and pepper',
      ],
      calories: 1961.9868245803752,
    },
  },

  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_17851827e873cf4833b80085934de06c',
      label: 'Creamy Paneer Gravy Recipe',
      image: 'https://i0.wp.com/gomathirecipes.com/wp-content/uploads/2022/06/paneer.jpg?resize=768%2C720&ssl=1',
      source: 'Food52',
      url: 'https://food52.com/recipes/41077-creamy-paneer-gravy-recipe',
      shareAs: 'http://www.edamam.com/recipe/creamy-paneer-gravy-recipe-17851827e873cf4833b80085934de06c/paneer+gravy',
      ingredientLines: [
        '1 cup Paneer',
        '1/2 cup Tomato (finely chopped)',
        '5 cloves Garlic (crushed)',
        '1 inch Ginger (crushed)',
        '1 piece Black Cardamom',
        '1 piece Cinamon Stick',
        '1 piece Bay leaf',
        '1 teaspoon Coriander Powder',
        '1 teaspoon Chicken Masala Powder',
        '1 teaspoon Garam Masala Powder',
        '1 teaspoon Red Chilli Powder',
        '1/4 teaspoon Turmeric Powder',
        '2 tablespoons Cashewnuts',
        '3/4 cup Fresh Cream (whipped)',
        '1/4 teaspoon Cumin Seeds',
        '1 tablespoon Oil',
        'Salt (to taste)',
        '2 tablespoons Coriander leaves',
        '1/2 cup Onion (to deep fry)',
        'Oil (to deep fry paneer and onion)',
      ],
      calories: 1881.1834508999473,
    },
  },
  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_4d2e1d89ee2aa05ef6b1e866ca47d1f7',
      label: 'Kadhai Paneer (Stir Fried Cheese and Peppers) Recipe',
      image: 'https://www.seriouseats.com/thmb/pvAbWyuugyTnRGH9dJGGavdnYPM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2013__08__20130812-kadhai-paneer-fb5c502485134cb38559141303a2d962.jpg',
      source: 'Serious Eats',
      url: 'http://www.seriouseats.com/recipes/2010/10/kadhai-paneer-stir-fry-cheese-peppers-indian-recipe.html',
      shareAs: 'http://www.edamam.com/recipe/kadhai-paneer-stir-fried-cheese-and-peppers-recipe-4d2e1d89ee2aa05ef6b1e866ca47d1f7/paneer+gravy',
      ingredientLines: [
        '5 tablespoons clarified butter, neutral oil, or niter kibbeh, divided',
        'Pinch asafoetida',
        '1 1/2 tablespoons coriander seed, toasted and ground',
        '1 teaspoon fenugreek seed, toasted and ground',
        '1 teaspoon half-sharp Hungarian paprika',
        '2 medium onions, finely diced or grated',
        '2 large tomatoes, or 1 15 ounce can, diced',
        '1 pound paneer or other firm frying cheese, cut into 1/2 inch cubes',
        '2 large green bell peppers, cut into thin strips',
        '2 large red bell peppers, cut into thin strips',
        '1 tablespoon dried (2 tablespoons fresh) fenugreek leaves, crumbled',
        'Juice of 1-2 limes, to taste',
      ],
      calories: 2877.9602722001996,
    },
  },
  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_16539b7caf46e1f7c377d70462ee8ac4',
      label: 'Cauliflower Kofta in Tomato Gravy',
      image: 'https://honestcooking.com/wp-content/uploads/2012/06/Kofta.jpg',
      source: 'Honest Cooking',
      url: 'http://honestcooking.com/cauliflower-kofta-in-tomato-gravy/',
      shareAs: 'http://www.edamam.com/recipe/cauliflower-kofta-in-tomato-gravy-16539b7caf46e1f7c377d70462ee8ac4/paneer+gravy',
      ingredientLines: [
        '(kofta balls)',
        '1 cup cauliflower, grated',
        '½ cup fresh paneer (if store bought, you can just mash it up)',
        '½ cup potato, boiled and mashed',
        '¼ cup carrot, grated',
        '½ teaspoon cumin seed',
        '¼ teaspoon garam masala',
        '3 teaspoons cilantro, chopped',
        '2 teaspoons ginger, grated',
        '1 small green chili or ½ jalapeño, chopped',
        '1 teaspoon salt',
        '~3-4 tablespoons flour (all purpose, chickpea or corn)',
        '(tomato gravy)',
        '2 tablespoons oil or ghee',
        'Pinch of asafetida (hing)',
        '1 teaspoon cumin seed',
        '1 red onion',
        '2 cloves garlic',
        '1 inch ginger, grated',
        '2 medium size tomatoes, chopped',
        '1 tablespoon coriander powder',
        '1 teaspoon garam masala',
        '¼ teaspoon chili powder',
        '⅓ teaspoon turmeric',
        '½ teaspoon amchoor (dried mango powder), optional',
        'Paneer whey as needed or water to make it soupy',
        'Salt to taste',
        'Cilantro, chopped',
      ],
      calories: 726.9182152076953,
    },
  },

  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_63d585f1ec1a3f8338626e89b6933140',
      label: 'Cuban-Inspired Sandwich recipes',
      image: 'https://hips.hearstapps.com/thepioneerwoman/wp-content/uploads/2016/07/cuban-inspired-sandwich-01.jpg',
      source: 'Pioneer Woman',
      url: 'http://thepioneerwoman.com/food-and-friends/cuban-inspired-sandwich/',
      shareAs: 'http://www.edamam.com/recipe/cuban-inspired-sandwich-recipes-63d585f1ec1a3f8338626e89b6933140/sandwich',
      ingredientLines: [
        '1/2 cup Mayonnaise',
        '4 teaspoons Stone Ground Mustard, Or More To Taste',
        '4 Sandwich Buns (I Like Homemade)',
        '2 Tablespoons Plus 2 Teaspoons Soft Butter',
        '1-1/3 cup Warm Pulled Pork',
        '8 slices Warm Ham',
        '12 Large Dill Pickle Slices',
      ],
      calories: 2513.5042500034397,
    },
  },

  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_0fa5d99eec9f563a93a37578ace97965',
      label: 'Chickpea Potato Curry',
      image: 'https://www.simplyrecipes.com/thmb/IxxmqgtFQdR8EQI2lazuEUN9aKk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2007__05__chickpea-potato-curry-horiz-a-1800-904becf986f44541847dcb6b906ba3a2.jpg',
      source: 'Simply Recipes',
      url: 'http://simplyrecipes.com/recipes/chickpea_potato_curry/',
      shareAs: 'http://www.edamam.com/recipe/chickpea-potato-curry-0fa5d99eec9f563a93a37578ace97965/potato+curry',
      ingredientLines: [
        '2 1/2 cups vegetable broth',
        'Two 15-ounce cans chickpeas (garbanzo beans), drained and rinsed',
        "One 14 1/2-ounce can fire-roasted or stewed tomatoes with chiles (See Muir Glen. If you can't find canned tomatoes with chiles you can add half a 4-ounce can of diced green anaheim chiles to a 14.5 ounce can of tomatoes.)",
        '6 baby (new) Yukon Gold potatoes (about 12 ounces), quartered',
        '1 medium onion, diced (about 1 cup)',
        '1 Tbsp unsalted butter',
        '2 teaspoons minced ginger',
        '1-2 teaspoons salt',
        '1 teaspoon ground cumin',
        '1 teaspoon ground coriander',
        '1/2 teaspoon cayenne pepper',
      ],
      calories: 1694.0774498107003,
    },
  },
  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_485575e9ba599475b72f63f697fe8fca',
      label: 'Cauliflower & Potato Curry',
      image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-265459_12-80c2f4b.jpg?quality=90&webp=true&resize=440,400',
      source: 'BBC Good Food',
      url: 'http://www.bbcgoodfood.com/recipes/420629/',
      shareAs: 'http://www.edamam.com/recipe/cauliflower-potato-curry-485575e9ba599475b72f63f697fe8fca/potato+curry',
      ingredientLines: [
        '2.0 tbsp vegetable oil',
        '1.0 tsp curry powder , or to taste',
        '2 potatoes , cut into chunks',
        '1 cauliflower , cut into florets',
        '½ tsp sugar',
        'naan bread and natural yogurt, to serve',
        '1 large onion , chopped',
        '3 garlic cloves , finely chopped',
        '227.0g can chopped tomatoes',
        'handful coriander , roughly chopped, to serve',
        '1 small green chilli , halved lengthways',
        'large piece ginger , grated',
        '½ tsp turmeric',
        'squeeze lemon juice',
        '1.0 tsp ground cumin',
      ],
      calories: 927.6032000005064,
    },
  },
  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_d13651ce1c620a70b5170cf8fc4b4831',
      label: 'New Potato Curry',
      image: 'https://irepo.primecp.com/2016/03/259652/recipe-8382_Large600_ID-1459244.jpg?v=1459244',
      source: 'Cookstr',
      url: 'http://www.cookstr.com/recipes/new-potato-curry',
      shareAs: 'http://www.edamam.com/recipe/new-potato-curry-d13651ce1c620a70b5170cf8fc4b4831/potato+curry',
      ingredientLines: [
        '2 tbsp (25 ml) clarified butter or vegetable oil',
        '1 lb (500 g) small new potatoes, about 10 new potatoes (see Notes)',
        '2 onions, finely chopped',
        '1 clove garlic, minced',
        '1 tsp (2 ml) curry powder, preferably Madras',
        '½ tsp (2 ml) salt',
        '½ tsp (2 ml) cracked black peppercorns',
        '½ cup (125 ml) water or vegetable stock',
        '2 tbsp (25 ml) freshly squeezed lemon juice',
        '¼ cup (50 ml) finely chopped cilantro',
      ],
      calories: 656.2134378778178,
    },
  },

  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_61c68c5e83feda078d4cd2f178a8aba3',
      label: 'Cauliflower and Tofu Curry Recipe',
      image: 'https://www.seriouseats.com/thmb/RK1mFBBwhfL0Lt-rBpLbqO-v2Z0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2020__01__20200116-sheet-pan-cauliflower-tofu-vicky-wasik15-758cf448727f4d4885b9f5050e2b349f.jpg',
      source: 'Serious Eats',
      url: 'http://www.seriouseats.com/recipes/2011/02/cauliflower-and-tofu-curry-recipe.html',
      shareAs: 'http://www.edamam.com/recipe/cauliflower-and-tofu-curry-recipe-61c68c5e83feda078d4cd2f178a8aba3/curry',
      ingredientLines: [
        '3 tablespoons olive oil',
        '1 large yellow onion, finely chopped',
        '1 14-ounce package extra-firm tofu, drained, patted dry, and cut into 3/4-inch dice',
        '1 heaping tablespoon hot curry or vindaloo curry paste',
        '1 14.5-ounce can diced tomatoes',
        '1 head cauliflower, cut into 3/4-inch florets',
        'Cooked brown basmati rice, for serving',
      ],
      calories: 1131.6555772794445,
    },
  },
  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_b8d126947d802def1f795016d75297c4',
      label: 'Curry-Crusted Fish',
      image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-7841_12-d467704.jpg?quality=90&webp=true&resize=440,400',
      source: 'BBC Good Food',
      url: 'http://www.bbcgoodfood.com/recipes/4717/',
      shareAs: 'http://www.edamam.com/recipe/curry-crusted-fish-b8d126947d802def1f795016d75297c4/curry',
      ingredientLines: [
        '3 slices bread , about 85g/3oz in total',
        '1 lime',
        '1.0 tbsp Korma curry paste',
        '4 thick white fish fillets',
      ],
      calories: 716.9749125599999,
    },
  },

  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_34a4410adb1f92ac4b480c8595bf97fa',
      label: 'Curry Chicken Wings',
      image: 'https://whiteonricecouple.com/recipe/images/coconut-chicken-wings-with-curry-sauce-1.jpg',
      source: 'White On Rice Couple',
      url: 'http://whiteonricecouple.com/recipes/curry-chicken-wings/',
      shareAs: 'http://www.edamam.com/recipe/curry-chicken-wings-34a4410adb1f92ac4b480c8595bf97fa/curry',
      ingredientLines: [
        '5 lbs Chicken Wings, tips trimmed, wings cut into 2 pieces',
        '1/2 c Flour',
        '1/4 c Curry Powder',
        '14 oz Coconut Milk',
        '3 T Curry Powder',
        '3 T Honey',
        '1 1/2 T Fish Sauce',
        '1 1/2 T Chili Garlic Sauce',
      ],
      calories: 5516.404981292365,
    },
  },
  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_b639fcf8190eb6363de36a5cc134fc0c',
      label: 'Curry Rub',
      image: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fassets.marthastewart.com%2Fstyles%2Fwmax-300%2Fd9%2F14edf07_e%2F14edf07_e_vert.jpg%3Fitok%3Dzq7ImNbt&q=60',
      source: 'Martha Stewart',
      url: 'https://www.marthastewart.com/337591/curry-rub',
      shareAs: 'http://www.edamam.com/recipe/curry-rub-b639fcf8190eb6363de36a5cc134fc0c/curry',
      ingredientLines: [
        '4 teaspoons curry powder',
        '1 1/2 teaspoons ground coriander',
        '1 1/2 teaspoons coarse salt',
        '1 teaspoon ground ginger',
        '1 teaspoon ground cumin',
        '1/2 teaspoon ground pepper',
        '1/2 teaspoon sugar',
      ],
      calories: 59.7175,
    },
  }, {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_e4456795dfe1409f69629df1670a6494',
      label: 'Fruits Sandwich',
      image: 'https://i0.wp.com/theindianclaypot.com/wp-content/uploads/2017/02/FRUIT-SANDWICH-SMALLER.jpg?fit=1620%2C1080&ssl=1',
      source: 'Food52',
      url: 'https://food52.com/recipes/61017-fruits-sandwich',
      shareAs: 'http://www.edamam.com/recipe/fruits-sandwich-e4456795dfe1409f69629df1670a6494/sandwich',
      ingredientLines: [
        '100 milliliters heavy cream',
        '1 tablespoon sugar',
        '4 pieces white sandwich bread',
        '4 pieces strawberry',
        '1 piece banana',
        '2 pieces sliced kiwi',
        '8 pieces tangerine',
      ],
      calories: 1030.0766340634966,
    },
  },
  {
    recipe: {
      uri: 'http://www.edamam.com/ontologies/edamam.owl#recipe_2256482f9dc843a41d747ca9d76690e5',
      label: 'Turkey Club Sandwich recipes',
      image: 'https://www.foodrepublic.com/wp-content/uploads/2011/06/FR_Test_Kitchen_01-0843-1920x560.jpg',
      url: 'http://www.foodrepublic.com/recipes/turkey-club-sandwich-recipe/',
      shareAs: 'http://www.edamam.com/recipe/turkey-club-sandwich-recipes-2256482f9dc843a41d747ca9d76690e5/sandwich',
      ingredientLines: [
        '3 slices white sandwich bread, lightly toasted',
        '2 tablespoons mayonnaise',
        '1/2 pound turkey breast, thinly sliced',
        '4 slices thick-cut bacon, fried until crisp',
        '1 small tomato, sliced into rounds',
        '4 leaves lettuce, rinsed and dried',
      ],

      calories: 1291.1000104466216,
    },
  },
];

export default preloadedData;
